%% -*- coding: utf-8 -*-
%% @private
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.5.1
-module(clientProtos).

-export([encode_msg/2, encode_msg/3]).
-export([decode_msg/2, decode_msg/3]).
-export([merge_msgs/3, merge_msgs/4]).
-export([verify_msg/2, verify_msg/3]).
-export([get_msg_defs/0]).
-export([get_msg_names/0]).
-export([get_group_names/0]).
-export([get_msg_or_group_names/0]).
-export([get_enum_names/0]).
-export([find_msg_def/1, fetch_msg_def/1]).
-export([find_enum_def/1, fetch_enum_def/1]).
-export([enum_symbol_by_value/2, enum_value_by_symbol/2]).
-export([get_service_names/0]).
-export([get_service_def/1]).
-export([get_rpc_names/1]).
-export([find_rpc_def/2, fetch_rpc_def/2]).
-export([fqbin_to_service_name/1]).
-export([service_name_to_fqbin/1]).
-export([fqbins_to_service_and_rpc_name/2]).
-export([service_and_rpc_name_to_fqbins/2]).
-export([get_package_name/0]).
-export([uses_packages/0]).
-export([gpb_version_as_string/0, gpb_version_as_list/0]).


%% enumerated types

-export_type([]).

%% message types
-type 'Authentication'() ::
      #{username                => iolist(),        % = 1
        password                => iolist()         % = 2
       }.

-type 'Result'() ::
      #{result                  => boolean() | 0 | 1, % = 1
        entity                  => iolist()         % = 3
       }.

-type 'Bid'() ::
      #{company                 => iolist(),        % = 1
        amount                  => integer(),       % = 2, 32 bits
        interest                => integer()        % = 3, 32 bits
       }.

-type 'Subscription'() ::
      #{company                 => iolist(),        % = 1
        amount                  => integer()        % = 2, 32 bits
       }.

-type 'Auction'() ::
      #{amount                  => integer(),       % = 1, 32 bits
        interest                => integer()        % = 2, 32 bits
       }.

-type 'Emission'() ::
      #{amount                  => integer()        % = 1, 32 bits
       }.

-type 'Notification'() ::
      #{status                  => iolist(),        % = 1
        action                  => iolist(),        % = 2
        company                 => [iolist()]       % = 3
       }.

-export_type(['Authentication'/0, 'Result'/0, 'Bid'/0, 'Subscription'/0, 'Auction'/0, 'Emission'/0, 'Notification'/0]).

-spec encode_msg('Authentication'() | 'Result'() | 'Bid'() | 'Subscription'() | 'Auction'() | 'Emission'() | 'Notification'(), atom()) -> binary().
encode_msg(Msg, MsgName) when is_atom(MsgName) ->
    encode_msg(Msg, MsgName, []).

-spec encode_msg('Authentication'() | 'Result'() | 'Bid'() | 'Subscription'() | 'Auction'() | 'Emission'() | 'Notification'(), atom(), list()) -> binary().
encode_msg(Msg, MsgName, Opts) ->
    case proplists:get_bool(verify, Opts) of
      true -> verify_msg(Msg, MsgName, Opts);
      false -> ok
    end,
    TrUserData = proplists:get_value(user_data, Opts),
    case MsgName of
      'Authentication' ->
	  encode_msg_Authentication(id(Msg, TrUserData),
				    TrUserData);
      'Result' ->
	  encode_msg_Result(id(Msg, TrUserData), TrUserData);
      'Bid' ->
	  encode_msg_Bid(id(Msg, TrUserData), TrUserData);
      'Subscription' ->
	  encode_msg_Subscription(id(Msg, TrUserData),
				  TrUserData);
      'Auction' ->
	  encode_msg_Auction(id(Msg, TrUserData), TrUserData);
      'Emission' ->
	  encode_msg_Emission(id(Msg, TrUserData), TrUserData);
      'Notification' ->
	  encode_msg_Notification(id(Msg, TrUserData), TrUserData)
    end.


encode_msg_Authentication(Msg, TrUserData) ->
    encode_msg_Authentication(Msg, <<>>, TrUserData).


encode_msg_Authentication(#{} = M, Bin, TrUserData) ->
    B1 = case M of
	   #{username := F1} ->
	       begin
		 TrF1 = id(F1, TrUserData),
		 e_type_string(TrF1, <<Bin/binary, 10>>, TrUserData)
	       end;
	   _ -> Bin
	 end,
    case M of
      #{password := F2} ->
	  begin
	    TrF2 = id(F2, TrUserData),
	    e_type_string(TrF2, <<B1/binary, 18>>, TrUserData)
	  end;
      _ -> B1
    end.

encode_msg_Result(Msg, TrUserData) ->
    encode_msg_Result(Msg, <<>>, TrUserData).


encode_msg_Result(#{} = M, Bin, TrUserData) ->
    B1 = case M of
	   #{result := F1} ->
	       begin
		 TrF1 = id(F1, TrUserData),
		 e_type_bool(TrF1, <<Bin/binary, 8>>, TrUserData)
	       end;
	   _ -> Bin
	 end,
    case M of
      #{entity := F2} ->
	  begin
	    TrF2 = id(F2, TrUserData),
	    e_type_string(TrF2, <<B1/binary, 26>>, TrUserData)
	  end;
      _ -> B1
    end.

encode_msg_Bid(Msg, TrUserData) ->
    encode_msg_Bid(Msg, <<>>, TrUserData).


encode_msg_Bid(#{} = M, Bin, TrUserData) ->
    B1 = case M of
	   #{company := F1} ->
	       begin
		 TrF1 = id(F1, TrUserData),
		 e_type_string(TrF1, <<Bin/binary, 10>>, TrUserData)
	       end;
	   _ -> Bin
	 end,
    B2 = case M of
	   #{amount := F2} ->
	       begin
		 TrF2 = id(F2, TrUserData),
		 e_type_int32(TrF2, <<B1/binary, 16>>, TrUserData)
	       end;
	   _ -> B1
	 end,
    case M of
      #{interest := F3} ->
	  begin
	    TrF3 = id(F3, TrUserData),
	    e_type_int32(TrF3, <<B2/binary, 24>>, TrUserData)
	  end;
      _ -> B2
    end.

encode_msg_Subscription(Msg, TrUserData) ->
    encode_msg_Subscription(Msg, <<>>, TrUserData).


encode_msg_Subscription(#{} = M, Bin, TrUserData) ->
    B1 = case M of
	   #{company := F1} ->
	       begin
		 TrF1 = id(F1, TrUserData),
		 e_type_string(TrF1, <<Bin/binary, 10>>, TrUserData)
	       end;
	   _ -> Bin
	 end,
    case M of
      #{amount := F2} ->
	  begin
	    TrF2 = id(F2, TrUserData),
	    e_type_int32(TrF2, <<B1/binary, 16>>, TrUserData)
	  end;
      _ -> B1
    end.

encode_msg_Auction(Msg, TrUserData) ->
    encode_msg_Auction(Msg, <<>>, TrUserData).


encode_msg_Auction(#{} = M, Bin, TrUserData) ->
    B1 = case M of
	   #{amount := F1} ->
	       begin
		 TrF1 = id(F1, TrUserData),
		 e_type_int32(TrF1, <<Bin/binary, 8>>, TrUserData)
	       end;
	   _ -> Bin
	 end,
    case M of
      #{interest := F2} ->
	  begin
	    TrF2 = id(F2, TrUserData),
	    e_type_int32(TrF2, <<B1/binary, 16>>, TrUserData)
	  end;
      _ -> B1
    end.

encode_msg_Emission(Msg, TrUserData) ->
    encode_msg_Emission(Msg, <<>>, TrUserData).


encode_msg_Emission(#{} = M, Bin, TrUserData) ->
    case M of
      #{amount := F1} ->
	  begin
	    TrF1 = id(F1, TrUserData),
	    e_type_int32(TrF1, <<Bin/binary, 8>>, TrUserData)
	  end;
      _ -> Bin
    end.

encode_msg_Notification(Msg, TrUserData) ->
    encode_msg_Notification(Msg, <<>>, TrUserData).


encode_msg_Notification(#{} = M, Bin, TrUserData) ->
    B1 = case M of
	   #{status := F1} ->
	       begin
		 TrF1 = id(F1, TrUserData),
		 e_type_string(TrF1, <<Bin/binary, 10>>, TrUserData)
	       end;
	   _ -> Bin
	 end,
    B2 = case M of
	   #{action := F2} ->
	       begin
		 TrF2 = id(F2, TrUserData),
		 e_type_string(TrF2, <<B1/binary, 18>>, TrUserData)
	       end;
	   _ -> B1
	 end,
    case M of
      #{company := F3} ->
	  TrF3 = id(F3, TrUserData),
	  if TrF3 == [] -> B2;
	     true ->
		 e_field_Notification_company(TrF3, B2, TrUserData)
	  end;
      _ -> B2
    end.

e_field_Notification_company([Elem | Rest], Bin,
			     TrUserData) ->
    Bin2 = <<Bin/binary, 26>>,
    Bin3 = e_type_string(id(Elem, TrUserData), Bin2,
			 TrUserData),
    e_field_Notification_company(Rest, Bin3, TrUserData);
e_field_Notification_company([], Bin, _TrUserData) ->
    Bin.

-compile({nowarn_unused_function,e_type_sint/3}).
e_type_sint(Value, Bin, _TrUserData) when Value >= 0 ->
    e_varint(Value * 2, Bin);
e_type_sint(Value, Bin, _TrUserData) ->
    e_varint(Value * -2 - 1, Bin).

-compile({nowarn_unused_function,e_type_int32/3}).
e_type_int32(Value, Bin, _TrUserData)
    when 0 =< Value, Value =< 127 ->
    <<Bin/binary, Value>>;
e_type_int32(Value, Bin, _TrUserData) ->
    <<N:64/unsigned-native>> = <<Value:64/signed-native>>,
    e_varint(N, Bin).

-compile({nowarn_unused_function,e_type_int64/3}).
e_type_int64(Value, Bin, _TrUserData)
    when 0 =< Value, Value =< 127 ->
    <<Bin/binary, Value>>;
e_type_int64(Value, Bin, _TrUserData) ->
    <<N:64/unsigned-native>> = <<Value:64/signed-native>>,
    e_varint(N, Bin).

-compile({nowarn_unused_function,e_type_bool/3}).
e_type_bool(true, Bin, _TrUserData) ->
    <<Bin/binary, 1>>;
e_type_bool(false, Bin, _TrUserData) ->
    <<Bin/binary, 0>>;
e_type_bool(1, Bin, _TrUserData) -> <<Bin/binary, 1>>;
e_type_bool(0, Bin, _TrUserData) -> <<Bin/binary, 0>>.

-compile({nowarn_unused_function,e_type_string/3}).
e_type_string(S, Bin, _TrUserData) ->
    Utf8 = unicode:characters_to_binary(S),
    Bin2 = e_varint(byte_size(Utf8), Bin),
    <<Bin2/binary, Utf8/binary>>.

-compile({nowarn_unused_function,e_type_bytes/3}).
e_type_bytes(Bytes, Bin, _TrUserData)
    when is_binary(Bytes) ->
    Bin2 = e_varint(byte_size(Bytes), Bin),
    <<Bin2/binary, Bytes/binary>>;
e_type_bytes(Bytes, Bin, _TrUserData)
    when is_list(Bytes) ->
    BytesBin = iolist_to_binary(Bytes),
    Bin2 = e_varint(byte_size(BytesBin), Bin),
    <<Bin2/binary, BytesBin/binary>>.

-compile({nowarn_unused_function,e_type_fixed32/3}).
e_type_fixed32(Value, Bin, _TrUserData) ->
    <<Bin/binary, Value:32/little>>.

-compile({nowarn_unused_function,e_type_sfixed32/3}).
e_type_sfixed32(Value, Bin, _TrUserData) ->
    <<Bin/binary, Value:32/little-signed>>.

-compile({nowarn_unused_function,e_type_fixed64/3}).
e_type_fixed64(Value, Bin, _TrUserData) ->
    <<Bin/binary, Value:64/little>>.

-compile({nowarn_unused_function,e_type_sfixed64/3}).
e_type_sfixed64(Value, Bin, _TrUserData) ->
    <<Bin/binary, Value:64/little-signed>>.

-compile({nowarn_unused_function,e_type_float/3}).
e_type_float(V, Bin, _) when is_number(V) ->
    <<Bin/binary, V:32/little-float>>;
e_type_float(infinity, Bin, _) ->
    <<Bin/binary, 0:16, 128, 127>>;
e_type_float('-infinity', Bin, _) ->
    <<Bin/binary, 0:16, 128, 255>>;
e_type_float(nan, Bin, _) ->
    <<Bin/binary, 0:16, 192, 127>>.

-compile({nowarn_unused_function,e_type_double/3}).
e_type_double(V, Bin, _) when is_number(V) ->
    <<Bin/binary, V:64/little-float>>;
e_type_double(infinity, Bin, _) ->
    <<Bin/binary, 0:48, 240, 127>>;
e_type_double('-infinity', Bin, _) ->
    <<Bin/binary, 0:48, 240, 255>>;
e_type_double(nan, Bin, _) ->
    <<Bin/binary, 0:48, 248, 127>>.

-compile({nowarn_unused_function,e_varint/3}).
e_varint(N, Bin, _TrUserData) -> e_varint(N, Bin).

-compile({nowarn_unused_function,e_varint/2}).
e_varint(N, Bin) when N =< 127 -> <<Bin/binary, N>>;
e_varint(N, Bin) ->
    Bin2 = <<Bin/binary, (N band 127 bor 128)>>,
    e_varint(N bsr 7, Bin2).


decode_msg(Bin, MsgName) when is_binary(Bin) ->
    decode_msg(Bin, MsgName, []).

decode_msg(Bin, MsgName, Opts) when is_binary(Bin) ->
    TrUserData = proplists:get_value(user_data, Opts),
    decode_msg_1_catch(Bin, MsgName, TrUserData).

-ifdef('OTP_RELEASE').
decode_msg_1_catch(Bin, MsgName, TrUserData) ->
    try decode_msg_2_doit(MsgName, Bin, TrUserData)
    catch Class:Reason:StackTrace -> error({gpb_error,{decoding_failure, {Bin, MsgName, {Class, Reason, StackTrace}}}})
    end.
-else.
decode_msg_1_catch(Bin, MsgName, TrUserData) ->
    try decode_msg_2_doit(MsgName, Bin, TrUserData)
    catch Class:Reason ->
        StackTrace = erlang:get_stacktrace(),
        error({gpb_error,{decoding_failure, {Bin, MsgName, {Class, Reason, StackTrace}}}})
    end.
-endif.

decode_msg_2_doit('Authentication', Bin, TrUserData) ->
    id(decode_msg_Authentication(Bin, TrUserData),
       TrUserData);
decode_msg_2_doit('Result', Bin, TrUserData) ->
    id(decode_msg_Result(Bin, TrUserData), TrUserData);
decode_msg_2_doit('Bid', Bin, TrUserData) ->
    id(decode_msg_Bid(Bin, TrUserData), TrUserData);
decode_msg_2_doit('Subscription', Bin, TrUserData) ->
    id(decode_msg_Subscription(Bin, TrUserData),
       TrUserData);
decode_msg_2_doit('Auction', Bin, TrUserData) ->
    id(decode_msg_Auction(Bin, TrUserData), TrUserData);
decode_msg_2_doit('Emission', Bin, TrUserData) ->
    id(decode_msg_Emission(Bin, TrUserData), TrUserData);
decode_msg_2_doit('Notification', Bin, TrUserData) ->
    id(decode_msg_Notification(Bin, TrUserData),
       TrUserData).



decode_msg_Authentication(Bin, TrUserData) ->
    dfp_read_field_def_Authentication(Bin, 0, 0,
				      id('$undef', TrUserData),
				      id('$undef', TrUserData), TrUserData).

dfp_read_field_def_Authentication(<<10, Rest/binary>>,
				  Z1, Z2, F@_1, F@_2, TrUserData) ->
    d_field_Authentication_username(Rest, Z1, Z2, F@_1,
				    F@_2, TrUserData);
dfp_read_field_def_Authentication(<<18, Rest/binary>>,
				  Z1, Z2, F@_1, F@_2, TrUserData) ->
    d_field_Authentication_password(Rest, Z1, Z2, F@_1,
				    F@_2, TrUserData);
dfp_read_field_def_Authentication(<<>>, 0, 0, F@_1,
				  F@_2, _) ->
    S1 = #{},
    S2 = if F@_1 == '$undef' -> S1;
	    true -> S1#{username => F@_1}
	 end,
    if F@_2 == '$undef' -> S2;
       true -> S2#{password => F@_2}
    end;
dfp_read_field_def_Authentication(Other, Z1, Z2, F@_1,
				  F@_2, TrUserData) ->
    dg_read_field_def_Authentication(Other, Z1, Z2, F@_1,
				     F@_2, TrUserData).

dg_read_field_def_Authentication(<<1:1, X:7,
				   Rest/binary>>,
				 N, Acc, F@_1, F@_2, TrUserData)
    when N < 32 - 7 ->
    dg_read_field_def_Authentication(Rest, N + 7,
				     X bsl N + Acc, F@_1, F@_2, TrUserData);
dg_read_field_def_Authentication(<<0:1, X:7,
				   Rest/binary>>,
				 N, Acc, F@_1, F@_2, TrUserData) ->
    Key = X bsl N + Acc,
    case Key of
      10 ->
	  d_field_Authentication_username(Rest, 0, 0, F@_1, F@_2,
					  TrUserData);
      18 ->
	  d_field_Authentication_password(Rest, 0, 0, F@_1, F@_2,
					  TrUserData);
      _ ->
	  case Key band 7 of
	    0 ->
		skip_varint_Authentication(Rest, 0, 0, F@_1, F@_2,
					   TrUserData);
	    1 ->
		skip_64_Authentication(Rest, 0, 0, F@_1, F@_2,
				       TrUserData);
	    2 ->
		skip_length_delimited_Authentication(Rest, 0, 0, F@_1,
						     F@_2, TrUserData);
	    3 ->
		skip_group_Authentication(Rest, Key bsr 3, 0, F@_1,
					  F@_2, TrUserData);
	    5 ->
		skip_32_Authentication(Rest, 0, 0, F@_1, F@_2,
				       TrUserData)
	  end
    end;
dg_read_field_def_Authentication(<<>>, 0, 0, F@_1, F@_2,
				 _) ->
    S1 = #{},
    S2 = if F@_1 == '$undef' -> S1;
	    true -> S1#{username => F@_1}
	 end,
    if F@_2 == '$undef' -> S2;
       true -> S2#{password => F@_2}
    end.

d_field_Authentication_username(<<1:1, X:7,
				  Rest/binary>>,
				N, Acc, F@_1, F@_2, TrUserData)
    when N < 57 ->
    d_field_Authentication_username(Rest, N + 7,
				    X bsl N + Acc, F@_1, F@_2, TrUserData);
d_field_Authentication_username(<<0:1, X:7,
				  Rest/binary>>,
				N, Acc, _, F@_2, TrUserData) ->
    {NewFValue, RestF} = begin
			   Len = X bsl N + Acc,
			   <<Utf8:Len/binary, Rest2/binary>> = Rest,
			   {id(unicode:characters_to_list(Utf8, unicode),
			       TrUserData),
			    Rest2}
			 end,
    dfp_read_field_def_Authentication(RestF, 0, 0,
				      NewFValue, F@_2, TrUserData).

d_field_Authentication_password(<<1:1, X:7,
				  Rest/binary>>,
				N, Acc, F@_1, F@_2, TrUserData)
    when N < 57 ->
    d_field_Authentication_password(Rest, N + 7,
				    X bsl N + Acc, F@_1, F@_2, TrUserData);
d_field_Authentication_password(<<0:1, X:7,
				  Rest/binary>>,
				N, Acc, F@_1, _, TrUserData) ->
    {NewFValue, RestF} = begin
			   Len = X bsl N + Acc,
			   <<Utf8:Len/binary, Rest2/binary>> = Rest,
			   {id(unicode:characters_to_list(Utf8, unicode),
			       TrUserData),
			    Rest2}
			 end,
    dfp_read_field_def_Authentication(RestF, 0, 0, F@_1,
				      NewFValue, TrUserData).

skip_varint_Authentication(<<1:1, _:7, Rest/binary>>,
			   Z1, Z2, F@_1, F@_2, TrUserData) ->
    skip_varint_Authentication(Rest, Z1, Z2, F@_1, F@_2,
			       TrUserData);
skip_varint_Authentication(<<0:1, _:7, Rest/binary>>,
			   Z1, Z2, F@_1, F@_2, TrUserData) ->
    dfp_read_field_def_Authentication(Rest, Z1, Z2, F@_1,
				      F@_2, TrUserData).

skip_length_delimited_Authentication(<<1:1, X:7,
				       Rest/binary>>,
				     N, Acc, F@_1, F@_2, TrUserData)
    when N < 57 ->
    skip_length_delimited_Authentication(Rest, N + 7,
					 X bsl N + Acc, F@_1, F@_2, TrUserData);
skip_length_delimited_Authentication(<<0:1, X:7,
				       Rest/binary>>,
				     N, Acc, F@_1, F@_2, TrUserData) ->
    Length = X bsl N + Acc,
    <<_:Length/binary, Rest2/binary>> = Rest,
    dfp_read_field_def_Authentication(Rest2, 0, 0, F@_1,
				      F@_2, TrUserData).

skip_group_Authentication(Bin, FNum, Z2, F@_1, F@_2,
			  TrUserData) ->
    {_, Rest} = read_group(Bin, FNum),
    dfp_read_field_def_Authentication(Rest, 0, Z2, F@_1,
				      F@_2, TrUserData).

skip_32_Authentication(<<_:32, Rest/binary>>, Z1, Z2,
		       F@_1, F@_2, TrUserData) ->
    dfp_read_field_def_Authentication(Rest, Z1, Z2, F@_1,
				      F@_2, TrUserData).

skip_64_Authentication(<<_:64, Rest/binary>>, Z1, Z2,
		       F@_1, F@_2, TrUserData) ->
    dfp_read_field_def_Authentication(Rest, Z1, Z2, F@_1,
				      F@_2, TrUserData).

decode_msg_Result(Bin, TrUserData) ->
    dfp_read_field_def_Result(Bin, 0, 0,
			      id('$undef', TrUserData),
			      id('$undef', TrUserData), TrUserData).

dfp_read_field_def_Result(<<8, Rest/binary>>, Z1, Z2,
			  F@_1, F@_2, TrUserData) ->
    d_field_Result_result(Rest, Z1, Z2, F@_1, F@_2,
			  TrUserData);
dfp_read_field_def_Result(<<26, Rest/binary>>, Z1, Z2,
			  F@_1, F@_2, TrUserData) ->
    d_field_Result_entity(Rest, Z1, Z2, F@_1, F@_2,
			  TrUserData);
dfp_read_field_def_Result(<<>>, 0, 0, F@_1, F@_2, _) ->
    S1 = #{},
    S2 = if F@_1 == '$undef' -> S1;
	    true -> S1#{result => F@_1}
	 end,
    if F@_2 == '$undef' -> S2;
       true -> S2#{entity => F@_2}
    end;
dfp_read_field_def_Result(Other, Z1, Z2, F@_1, F@_2,
			  TrUserData) ->
    dg_read_field_def_Result(Other, Z1, Z2, F@_1, F@_2,
			     TrUserData).

dg_read_field_def_Result(<<1:1, X:7, Rest/binary>>, N,
			 Acc, F@_1, F@_2, TrUserData)
    when N < 32 - 7 ->
    dg_read_field_def_Result(Rest, N + 7, X bsl N + Acc,
			     F@_1, F@_2, TrUserData);
dg_read_field_def_Result(<<0:1, X:7, Rest/binary>>, N,
			 Acc, F@_1, F@_2, TrUserData) ->
    Key = X bsl N + Acc,
    case Key of
      8 ->
	  d_field_Result_result(Rest, 0, 0, F@_1, F@_2,
				TrUserData);
      26 ->
	  d_field_Result_entity(Rest, 0, 0, F@_1, F@_2,
				TrUserData);
      _ ->
	  case Key band 7 of
	    0 ->
		skip_varint_Result(Rest, 0, 0, F@_1, F@_2, TrUserData);
	    1 -> skip_64_Result(Rest, 0, 0, F@_1, F@_2, TrUserData);
	    2 ->
		skip_length_delimited_Result(Rest, 0, 0, F@_1, F@_2,
					     TrUserData);
	    3 ->
		skip_group_Result(Rest, Key bsr 3, 0, F@_1, F@_2,
				  TrUserData);
	    5 -> skip_32_Result(Rest, 0, 0, F@_1, F@_2, TrUserData)
	  end
    end;
dg_read_field_def_Result(<<>>, 0, 0, F@_1, F@_2, _) ->
    S1 = #{},
    S2 = if F@_1 == '$undef' -> S1;
	    true -> S1#{result => F@_1}
	 end,
    if F@_2 == '$undef' -> S2;
       true -> S2#{entity => F@_2}
    end.

d_field_Result_result(<<1:1, X:7, Rest/binary>>, N, Acc,
		      F@_1, F@_2, TrUserData)
    when N < 57 ->
    d_field_Result_result(Rest, N + 7, X bsl N + Acc, F@_1,
			  F@_2, TrUserData);
d_field_Result_result(<<0:1, X:7, Rest/binary>>, N, Acc,
		      _, F@_2, TrUserData) ->
    {NewFValue, RestF} = {id(X bsl N + Acc =/= 0,
			     TrUserData),
			  Rest},
    dfp_read_field_def_Result(RestF, 0, 0, NewFValue, F@_2,
			      TrUserData).

d_field_Result_entity(<<1:1, X:7, Rest/binary>>, N, Acc,
		      F@_1, F@_2, TrUserData)
    when N < 57 ->
    d_field_Result_entity(Rest, N + 7, X bsl N + Acc, F@_1,
			  F@_2, TrUserData);
d_field_Result_entity(<<0:1, X:7, Rest/binary>>, N, Acc,
		      F@_1, _, TrUserData) ->
    {NewFValue, RestF} = begin
			   Len = X bsl N + Acc,
			   <<Utf8:Len/binary, Rest2/binary>> = Rest,
			   {id(unicode:characters_to_list(Utf8, unicode),
			       TrUserData),
			    Rest2}
			 end,
    dfp_read_field_def_Result(RestF, 0, 0, F@_1, NewFValue,
			      TrUserData).

skip_varint_Result(<<1:1, _:7, Rest/binary>>, Z1, Z2,
		   F@_1, F@_2, TrUserData) ->
    skip_varint_Result(Rest, Z1, Z2, F@_1, F@_2,
		       TrUserData);
skip_varint_Result(<<0:1, _:7, Rest/binary>>, Z1, Z2,
		   F@_1, F@_2, TrUserData) ->
    dfp_read_field_def_Result(Rest, Z1, Z2, F@_1, F@_2,
			      TrUserData).

skip_length_delimited_Result(<<1:1, X:7, Rest/binary>>,
			     N, Acc, F@_1, F@_2, TrUserData)
    when N < 57 ->
    skip_length_delimited_Result(Rest, N + 7, X bsl N + Acc,
				 F@_1, F@_2, TrUserData);
skip_length_delimited_Result(<<0:1, X:7, Rest/binary>>,
			     N, Acc, F@_1, F@_2, TrUserData) ->
    Length = X bsl N + Acc,
    <<_:Length/binary, Rest2/binary>> = Rest,
    dfp_read_field_def_Result(Rest2, 0, 0, F@_1, F@_2,
			      TrUserData).

skip_group_Result(Bin, FNum, Z2, F@_1, F@_2,
		  TrUserData) ->
    {_, Rest} = read_group(Bin, FNum),
    dfp_read_field_def_Result(Rest, 0, Z2, F@_1, F@_2,
			      TrUserData).

skip_32_Result(<<_:32, Rest/binary>>, Z1, Z2, F@_1,
	       F@_2, TrUserData) ->
    dfp_read_field_def_Result(Rest, Z1, Z2, F@_1, F@_2,
			      TrUserData).

skip_64_Result(<<_:64, Rest/binary>>, Z1, Z2, F@_1,
	       F@_2, TrUserData) ->
    dfp_read_field_def_Result(Rest, Z1, Z2, F@_1, F@_2,
			      TrUserData).

decode_msg_Bid(Bin, TrUserData) ->
    dfp_read_field_def_Bid(Bin, 0, 0,
			   id('$undef', TrUserData), id('$undef', TrUserData),
			   id('$undef', TrUserData), TrUserData).

dfp_read_field_def_Bid(<<10, Rest/binary>>, Z1, Z2,
		       F@_1, F@_2, F@_3, TrUserData) ->
    d_field_Bid_company(Rest, Z1, Z2, F@_1, F@_2, F@_3,
			TrUserData);
dfp_read_field_def_Bid(<<16, Rest/binary>>, Z1, Z2,
		       F@_1, F@_2, F@_3, TrUserData) ->
    d_field_Bid_amount(Rest, Z1, Z2, F@_1, F@_2, F@_3,
		       TrUserData);
dfp_read_field_def_Bid(<<24, Rest/binary>>, Z1, Z2,
		       F@_1, F@_2, F@_3, TrUserData) ->
    d_field_Bid_interest(Rest, Z1, Z2, F@_1, F@_2, F@_3,
			 TrUserData);
dfp_read_field_def_Bid(<<>>, 0, 0, F@_1, F@_2, F@_3,
		       _) ->
    S1 = #{},
    S2 = if F@_1 == '$undef' -> S1;
	    true -> S1#{company => F@_1}
	 end,
    S3 = if F@_2 == '$undef' -> S2;
	    true -> S2#{amount => F@_2}
	 end,
    if F@_3 == '$undef' -> S3;
       true -> S3#{interest => F@_3}
    end;
dfp_read_field_def_Bid(Other, Z1, Z2, F@_1, F@_2, F@_3,
		       TrUserData) ->
    dg_read_field_def_Bid(Other, Z1, Z2, F@_1, F@_2, F@_3,
			  TrUserData).

dg_read_field_def_Bid(<<1:1, X:7, Rest/binary>>, N, Acc,
		      F@_1, F@_2, F@_3, TrUserData)
    when N < 32 - 7 ->
    dg_read_field_def_Bid(Rest, N + 7, X bsl N + Acc, F@_1,
			  F@_2, F@_3, TrUserData);
dg_read_field_def_Bid(<<0:1, X:7, Rest/binary>>, N, Acc,
		      F@_1, F@_2, F@_3, TrUserData) ->
    Key = X bsl N + Acc,
    case Key of
      10 ->
	  d_field_Bid_company(Rest, 0, 0, F@_1, F@_2, F@_3,
			      TrUserData);
      16 ->
	  d_field_Bid_amount(Rest, 0, 0, F@_1, F@_2, F@_3,
			     TrUserData);
      24 ->
	  d_field_Bid_interest(Rest, 0, 0, F@_1, F@_2, F@_3,
			       TrUserData);
      _ ->
	  case Key band 7 of
	    0 ->
		skip_varint_Bid(Rest, 0, 0, F@_1, F@_2, F@_3,
				TrUserData);
	    1 ->
		skip_64_Bid(Rest, 0, 0, F@_1, F@_2, F@_3, TrUserData);
	    2 ->
		skip_length_delimited_Bid(Rest, 0, 0, F@_1, F@_2, F@_3,
					  TrUserData);
	    3 ->
		skip_group_Bid(Rest, Key bsr 3, 0, F@_1, F@_2, F@_3,
			       TrUserData);
	    5 ->
		skip_32_Bid(Rest, 0, 0, F@_1, F@_2, F@_3, TrUserData)
	  end
    end;
dg_read_field_def_Bid(<<>>, 0, 0, F@_1, F@_2, F@_3,
		      _) ->
    S1 = #{},
    S2 = if F@_1 == '$undef' -> S1;
	    true -> S1#{company => F@_1}
	 end,
    S3 = if F@_2 == '$undef' -> S2;
	    true -> S2#{amount => F@_2}
	 end,
    if F@_3 == '$undef' -> S3;
       true -> S3#{interest => F@_3}
    end.

d_field_Bid_company(<<1:1, X:7, Rest/binary>>, N, Acc,
		    F@_1, F@_2, F@_3, TrUserData)
    when N < 57 ->
    d_field_Bid_company(Rest, N + 7, X bsl N + Acc, F@_1,
			F@_2, F@_3, TrUserData);
d_field_Bid_company(<<0:1, X:7, Rest/binary>>, N, Acc,
		    _, F@_2, F@_3, TrUserData) ->
    {NewFValue, RestF} = begin
			   Len = X bsl N + Acc,
			   <<Utf8:Len/binary, Rest2/binary>> = Rest,
			   {id(unicode:characters_to_list(Utf8, unicode),
			       TrUserData),
			    Rest2}
			 end,
    dfp_read_field_def_Bid(RestF, 0, 0, NewFValue, F@_2,
			   F@_3, TrUserData).

d_field_Bid_amount(<<1:1, X:7, Rest/binary>>, N, Acc,
		   F@_1, F@_2, F@_3, TrUserData)
    when N < 57 ->
    d_field_Bid_amount(Rest, N + 7, X bsl N + Acc, F@_1,
		       F@_2, F@_3, TrUserData);
d_field_Bid_amount(<<0:1, X:7, Rest/binary>>, N, Acc,
		   F@_1, _, F@_3, TrUserData) ->
    {NewFValue, RestF} = {begin
			    <<Res:32/signed-native>> = <<(X bsl N +
							    Acc):32/unsigned-native>>,
			    id(Res, TrUserData)
			  end,
			  Rest},
    dfp_read_field_def_Bid(RestF, 0, 0, F@_1, NewFValue,
			   F@_3, TrUserData).

d_field_Bid_interest(<<1:1, X:7, Rest/binary>>, N, Acc,
		     F@_1, F@_2, F@_3, TrUserData)
    when N < 57 ->
    d_field_Bid_interest(Rest, N + 7, X bsl N + Acc, F@_1,
			 F@_2, F@_3, TrUserData);
d_field_Bid_interest(<<0:1, X:7, Rest/binary>>, N, Acc,
		     F@_1, F@_2, _, TrUserData) ->
    {NewFValue, RestF} = {begin
			    <<Res:32/signed-native>> = <<(X bsl N +
							    Acc):32/unsigned-native>>,
			    id(Res, TrUserData)
			  end,
			  Rest},
    dfp_read_field_def_Bid(RestF, 0, 0, F@_1, F@_2,
			   NewFValue, TrUserData).

skip_varint_Bid(<<1:1, _:7, Rest/binary>>, Z1, Z2, F@_1,
		F@_2, F@_3, TrUserData) ->
    skip_varint_Bid(Rest, Z1, Z2, F@_1, F@_2, F@_3,
		    TrUserData);
skip_varint_Bid(<<0:1, _:7, Rest/binary>>, Z1, Z2, F@_1,
		F@_2, F@_3, TrUserData) ->
    dfp_read_field_def_Bid(Rest, Z1, Z2, F@_1, F@_2, F@_3,
			   TrUserData).

skip_length_delimited_Bid(<<1:1, X:7, Rest/binary>>, N,
			  Acc, F@_1, F@_2, F@_3, TrUserData)
    when N < 57 ->
    skip_length_delimited_Bid(Rest, N + 7, X bsl N + Acc,
			      F@_1, F@_2, F@_3, TrUserData);
skip_length_delimited_Bid(<<0:1, X:7, Rest/binary>>, N,
			  Acc, F@_1, F@_2, F@_3, TrUserData) ->
    Length = X bsl N + Acc,
    <<_:Length/binary, Rest2/binary>> = Rest,
    dfp_read_field_def_Bid(Rest2, 0, 0, F@_1, F@_2, F@_3,
			   TrUserData).

skip_group_Bid(Bin, FNum, Z2, F@_1, F@_2, F@_3,
	       TrUserData) ->
    {_, Rest} = read_group(Bin, FNum),
    dfp_read_field_def_Bid(Rest, 0, Z2, F@_1, F@_2, F@_3,
			   TrUserData).

skip_32_Bid(<<_:32, Rest/binary>>, Z1, Z2, F@_1, F@_2,
	    F@_3, TrUserData) ->
    dfp_read_field_def_Bid(Rest, Z1, Z2, F@_1, F@_2, F@_3,
			   TrUserData).

skip_64_Bid(<<_:64, Rest/binary>>, Z1, Z2, F@_1, F@_2,
	    F@_3, TrUserData) ->
    dfp_read_field_def_Bid(Rest, Z1, Z2, F@_1, F@_2, F@_3,
			   TrUserData).

decode_msg_Subscription(Bin, TrUserData) ->
    dfp_read_field_def_Subscription(Bin, 0, 0,
				    id('$undef', TrUserData),
				    id('$undef', TrUserData), TrUserData).

dfp_read_field_def_Subscription(<<10, Rest/binary>>, Z1,
				Z2, F@_1, F@_2, TrUserData) ->
    d_field_Subscription_company(Rest, Z1, Z2, F@_1, F@_2,
				 TrUserData);
dfp_read_field_def_Subscription(<<16, Rest/binary>>, Z1,
				Z2, F@_1, F@_2, TrUserData) ->
    d_field_Subscription_amount(Rest, Z1, Z2, F@_1, F@_2,
				TrUserData);
dfp_read_field_def_Subscription(<<>>, 0, 0, F@_1, F@_2,
				_) ->
    S1 = #{},
    S2 = if F@_1 == '$undef' -> S1;
	    true -> S1#{company => F@_1}
	 end,
    if F@_2 == '$undef' -> S2;
       true -> S2#{amount => F@_2}
    end;
dfp_read_field_def_Subscription(Other, Z1, Z2, F@_1,
				F@_2, TrUserData) ->
    dg_read_field_def_Subscription(Other, Z1, Z2, F@_1,
				   F@_2, TrUserData).

dg_read_field_def_Subscription(<<1:1, X:7,
				 Rest/binary>>,
			       N, Acc, F@_1, F@_2, TrUserData)
    when N < 32 - 7 ->
    dg_read_field_def_Subscription(Rest, N + 7,
				   X bsl N + Acc, F@_1, F@_2, TrUserData);
dg_read_field_def_Subscription(<<0:1, X:7,
				 Rest/binary>>,
			       N, Acc, F@_1, F@_2, TrUserData) ->
    Key = X bsl N + Acc,
    case Key of
      10 ->
	  d_field_Subscription_company(Rest, 0, 0, F@_1, F@_2,
				       TrUserData);
      16 ->
	  d_field_Subscription_amount(Rest, 0, 0, F@_1, F@_2,
				      TrUserData);
      _ ->
	  case Key band 7 of
	    0 ->
		skip_varint_Subscription(Rest, 0, 0, F@_1, F@_2,
					 TrUserData);
	    1 ->
		skip_64_Subscription(Rest, 0, 0, F@_1, F@_2,
				     TrUserData);
	    2 ->
		skip_length_delimited_Subscription(Rest, 0, 0, F@_1,
						   F@_2, TrUserData);
	    3 ->
		skip_group_Subscription(Rest, Key bsr 3, 0, F@_1, F@_2,
					TrUserData);
	    5 ->
		skip_32_Subscription(Rest, 0, 0, F@_1, F@_2, TrUserData)
	  end
    end;
dg_read_field_def_Subscription(<<>>, 0, 0, F@_1, F@_2,
			       _) ->
    S1 = #{},
    S2 = if F@_1 == '$undef' -> S1;
	    true -> S1#{company => F@_1}
	 end,
    if F@_2 == '$undef' -> S2;
       true -> S2#{amount => F@_2}
    end.

d_field_Subscription_company(<<1:1, X:7, Rest/binary>>,
			     N, Acc, F@_1, F@_2, TrUserData)
    when N < 57 ->
    d_field_Subscription_company(Rest, N + 7, X bsl N + Acc,
				 F@_1, F@_2, TrUserData);
d_field_Subscription_company(<<0:1, X:7, Rest/binary>>,
			     N, Acc, _, F@_2, TrUserData) ->
    {NewFValue, RestF} = begin
			   Len = X bsl N + Acc,
			   <<Utf8:Len/binary, Rest2/binary>> = Rest,
			   {id(unicode:characters_to_list(Utf8, unicode),
			       TrUserData),
			    Rest2}
			 end,
    dfp_read_field_def_Subscription(RestF, 0, 0, NewFValue,
				    F@_2, TrUserData).

d_field_Subscription_amount(<<1:1, X:7, Rest/binary>>,
			    N, Acc, F@_1, F@_2, TrUserData)
    when N < 57 ->
    d_field_Subscription_amount(Rest, N + 7, X bsl N + Acc,
				F@_1, F@_2, TrUserData);
d_field_Subscription_amount(<<0:1, X:7, Rest/binary>>,
			    N, Acc, F@_1, _, TrUserData) ->
    {NewFValue, RestF} = {begin
			    <<Res:32/signed-native>> = <<(X bsl N +
							    Acc):32/unsigned-native>>,
			    id(Res, TrUserData)
			  end,
			  Rest},
    dfp_read_field_def_Subscription(RestF, 0, 0, F@_1,
				    NewFValue, TrUserData).

skip_varint_Subscription(<<1:1, _:7, Rest/binary>>, Z1,
			 Z2, F@_1, F@_2, TrUserData) ->
    skip_varint_Subscription(Rest, Z1, Z2, F@_1, F@_2,
			     TrUserData);
skip_varint_Subscription(<<0:1, _:7, Rest/binary>>, Z1,
			 Z2, F@_1, F@_2, TrUserData) ->
    dfp_read_field_def_Subscription(Rest, Z1, Z2, F@_1,
				    F@_2, TrUserData).

skip_length_delimited_Subscription(<<1:1, X:7,
				     Rest/binary>>,
				   N, Acc, F@_1, F@_2, TrUserData)
    when N < 57 ->
    skip_length_delimited_Subscription(Rest, N + 7,
				       X bsl N + Acc, F@_1, F@_2, TrUserData);
skip_length_delimited_Subscription(<<0:1, X:7,
				     Rest/binary>>,
				   N, Acc, F@_1, F@_2, TrUserData) ->
    Length = X bsl N + Acc,
    <<_:Length/binary, Rest2/binary>> = Rest,
    dfp_read_field_def_Subscription(Rest2, 0, 0, F@_1, F@_2,
				    TrUserData).

skip_group_Subscription(Bin, FNum, Z2, F@_1, F@_2,
			TrUserData) ->
    {_, Rest} = read_group(Bin, FNum),
    dfp_read_field_def_Subscription(Rest, 0, Z2, F@_1, F@_2,
				    TrUserData).

skip_32_Subscription(<<_:32, Rest/binary>>, Z1, Z2,
		     F@_1, F@_2, TrUserData) ->
    dfp_read_field_def_Subscription(Rest, Z1, Z2, F@_1,
				    F@_2, TrUserData).

skip_64_Subscription(<<_:64, Rest/binary>>, Z1, Z2,
		     F@_1, F@_2, TrUserData) ->
    dfp_read_field_def_Subscription(Rest, Z1, Z2, F@_1,
				    F@_2, TrUserData).

decode_msg_Auction(Bin, TrUserData) ->
    dfp_read_field_def_Auction(Bin, 0, 0,
			       id('$undef', TrUserData),
			       id('$undef', TrUserData), TrUserData).

dfp_read_field_def_Auction(<<8, Rest/binary>>, Z1, Z2,
			   F@_1, F@_2, TrUserData) ->
    d_field_Auction_amount(Rest, Z1, Z2, F@_1, F@_2,
			   TrUserData);
dfp_read_field_def_Auction(<<16, Rest/binary>>, Z1, Z2,
			   F@_1, F@_2, TrUserData) ->
    d_field_Auction_interest(Rest, Z1, Z2, F@_1, F@_2,
			     TrUserData);
dfp_read_field_def_Auction(<<>>, 0, 0, F@_1, F@_2, _) ->
    S1 = #{},
    S2 = if F@_1 == '$undef' -> S1;
	    true -> S1#{amount => F@_1}
	 end,
    if F@_2 == '$undef' -> S2;
       true -> S2#{interest => F@_2}
    end;
dfp_read_field_def_Auction(Other, Z1, Z2, F@_1, F@_2,
			   TrUserData) ->
    dg_read_field_def_Auction(Other, Z1, Z2, F@_1, F@_2,
			      TrUserData).

dg_read_field_def_Auction(<<1:1, X:7, Rest/binary>>, N,
			  Acc, F@_1, F@_2, TrUserData)
    when N < 32 - 7 ->
    dg_read_field_def_Auction(Rest, N + 7, X bsl N + Acc,
			      F@_1, F@_2, TrUserData);
dg_read_field_def_Auction(<<0:1, X:7, Rest/binary>>, N,
			  Acc, F@_1, F@_2, TrUserData) ->
    Key = X bsl N + Acc,
    case Key of
      8 ->
	  d_field_Auction_amount(Rest, 0, 0, F@_1, F@_2,
				 TrUserData);
      16 ->
	  d_field_Auction_interest(Rest, 0, 0, F@_1, F@_2,
				   TrUserData);
      _ ->
	  case Key band 7 of
	    0 ->
		skip_varint_Auction(Rest, 0, 0, F@_1, F@_2, TrUserData);
	    1 ->
		skip_64_Auction(Rest, 0, 0, F@_1, F@_2, TrUserData);
	    2 ->
		skip_length_delimited_Auction(Rest, 0, 0, F@_1, F@_2,
					      TrUserData);
	    3 ->
		skip_group_Auction(Rest, Key bsr 3, 0, F@_1, F@_2,
				   TrUserData);
	    5 -> skip_32_Auction(Rest, 0, 0, F@_1, F@_2, TrUserData)
	  end
    end;
dg_read_field_def_Auction(<<>>, 0, 0, F@_1, F@_2, _) ->
    S1 = #{},
    S2 = if F@_1 == '$undef' -> S1;
	    true -> S1#{amount => F@_1}
	 end,
    if F@_2 == '$undef' -> S2;
       true -> S2#{interest => F@_2}
    end.

d_field_Auction_amount(<<1:1, X:7, Rest/binary>>, N,
		       Acc, F@_1, F@_2, TrUserData)
    when N < 57 ->
    d_field_Auction_amount(Rest, N + 7, X bsl N + Acc, F@_1,
			   F@_2, TrUserData);
d_field_Auction_amount(<<0:1, X:7, Rest/binary>>, N,
		       Acc, _, F@_2, TrUserData) ->
    {NewFValue, RestF} = {begin
			    <<Res:32/signed-native>> = <<(X bsl N +
							    Acc):32/unsigned-native>>,
			    id(Res, TrUserData)
			  end,
			  Rest},
    dfp_read_field_def_Auction(RestF, 0, 0, NewFValue, F@_2,
			       TrUserData).

d_field_Auction_interest(<<1:1, X:7, Rest/binary>>, N,
			 Acc, F@_1, F@_2, TrUserData)
    when N < 57 ->
    d_field_Auction_interest(Rest, N + 7, X bsl N + Acc,
			     F@_1, F@_2, TrUserData);
d_field_Auction_interest(<<0:1, X:7, Rest/binary>>, N,
			 Acc, F@_1, _, TrUserData) ->
    {NewFValue, RestF} = {begin
			    <<Res:32/signed-native>> = <<(X bsl N +
							    Acc):32/unsigned-native>>,
			    id(Res, TrUserData)
			  end,
			  Rest},
    dfp_read_field_def_Auction(RestF, 0, 0, F@_1, NewFValue,
			       TrUserData).

skip_varint_Auction(<<1:1, _:7, Rest/binary>>, Z1, Z2,
		    F@_1, F@_2, TrUserData) ->
    skip_varint_Auction(Rest, Z1, Z2, F@_1, F@_2,
			TrUserData);
skip_varint_Auction(<<0:1, _:7, Rest/binary>>, Z1, Z2,
		    F@_1, F@_2, TrUserData) ->
    dfp_read_field_def_Auction(Rest, Z1, Z2, F@_1, F@_2,
			       TrUserData).

skip_length_delimited_Auction(<<1:1, X:7, Rest/binary>>,
			      N, Acc, F@_1, F@_2, TrUserData)
    when N < 57 ->
    skip_length_delimited_Auction(Rest, N + 7,
				  X bsl N + Acc, F@_1, F@_2, TrUserData);
skip_length_delimited_Auction(<<0:1, X:7, Rest/binary>>,
			      N, Acc, F@_1, F@_2, TrUserData) ->
    Length = X bsl N + Acc,
    <<_:Length/binary, Rest2/binary>> = Rest,
    dfp_read_field_def_Auction(Rest2, 0, 0, F@_1, F@_2,
			       TrUserData).

skip_group_Auction(Bin, FNum, Z2, F@_1, F@_2,
		   TrUserData) ->
    {_, Rest} = read_group(Bin, FNum),
    dfp_read_field_def_Auction(Rest, 0, Z2, F@_1, F@_2,
			       TrUserData).

skip_32_Auction(<<_:32, Rest/binary>>, Z1, Z2, F@_1,
		F@_2, TrUserData) ->
    dfp_read_field_def_Auction(Rest, Z1, Z2, F@_1, F@_2,
			       TrUserData).

skip_64_Auction(<<_:64, Rest/binary>>, Z1, Z2, F@_1,
		F@_2, TrUserData) ->
    dfp_read_field_def_Auction(Rest, Z1, Z2, F@_1, F@_2,
			       TrUserData).

decode_msg_Emission(Bin, TrUserData) ->
    dfp_read_field_def_Emission(Bin, 0, 0,
				id('$undef', TrUserData), TrUserData).

dfp_read_field_def_Emission(<<8, Rest/binary>>, Z1, Z2,
			    F@_1, TrUserData) ->
    d_field_Emission_amount(Rest, Z1, Z2, F@_1, TrUserData);
dfp_read_field_def_Emission(<<>>, 0, 0, F@_1, _) ->
    S1 = #{},
    if F@_1 == '$undef' -> S1;
       true -> S1#{amount => F@_1}
    end;
dfp_read_field_def_Emission(Other, Z1, Z2, F@_1,
			    TrUserData) ->
    dg_read_field_def_Emission(Other, Z1, Z2, F@_1,
			       TrUserData).

dg_read_field_def_Emission(<<1:1, X:7, Rest/binary>>, N,
			   Acc, F@_1, TrUserData)
    when N < 32 - 7 ->
    dg_read_field_def_Emission(Rest, N + 7, X bsl N + Acc,
			       F@_1, TrUserData);
dg_read_field_def_Emission(<<0:1, X:7, Rest/binary>>, N,
			   Acc, F@_1, TrUserData) ->
    Key = X bsl N + Acc,
    case Key of
      8 ->
	  d_field_Emission_amount(Rest, 0, 0, F@_1, TrUserData);
      _ ->
	  case Key band 7 of
	    0 -> skip_varint_Emission(Rest, 0, 0, F@_1, TrUserData);
	    1 -> skip_64_Emission(Rest, 0, 0, F@_1, TrUserData);
	    2 ->
		skip_length_delimited_Emission(Rest, 0, 0, F@_1,
					       TrUserData);
	    3 ->
		skip_group_Emission(Rest, Key bsr 3, 0, F@_1,
				    TrUserData);
	    5 -> skip_32_Emission(Rest, 0, 0, F@_1, TrUserData)
	  end
    end;
dg_read_field_def_Emission(<<>>, 0, 0, F@_1, _) ->
    S1 = #{},
    if F@_1 == '$undef' -> S1;
       true -> S1#{amount => F@_1}
    end.

d_field_Emission_amount(<<1:1, X:7, Rest/binary>>, N,
			Acc, F@_1, TrUserData)
    when N < 57 ->
    d_field_Emission_amount(Rest, N + 7, X bsl N + Acc,
			    F@_1, TrUserData);
d_field_Emission_amount(<<0:1, X:7, Rest/binary>>, N,
			Acc, _, TrUserData) ->
    {NewFValue, RestF} = {begin
			    <<Res:32/signed-native>> = <<(X bsl N +
							    Acc):32/unsigned-native>>,
			    id(Res, TrUserData)
			  end,
			  Rest},
    dfp_read_field_def_Emission(RestF, 0, 0, NewFValue,
				TrUserData).

skip_varint_Emission(<<1:1, _:7, Rest/binary>>, Z1, Z2,
		     F@_1, TrUserData) ->
    skip_varint_Emission(Rest, Z1, Z2, F@_1, TrUserData);
skip_varint_Emission(<<0:1, _:7, Rest/binary>>, Z1, Z2,
		     F@_1, TrUserData) ->
    dfp_read_field_def_Emission(Rest, Z1, Z2, F@_1,
				TrUserData).

skip_length_delimited_Emission(<<1:1, X:7,
				 Rest/binary>>,
			       N, Acc, F@_1, TrUserData)
    when N < 57 ->
    skip_length_delimited_Emission(Rest, N + 7,
				   X bsl N + Acc, F@_1, TrUserData);
skip_length_delimited_Emission(<<0:1, X:7,
				 Rest/binary>>,
			       N, Acc, F@_1, TrUserData) ->
    Length = X bsl N + Acc,
    <<_:Length/binary, Rest2/binary>> = Rest,
    dfp_read_field_def_Emission(Rest2, 0, 0, F@_1,
				TrUserData).

skip_group_Emission(Bin, FNum, Z2, F@_1, TrUserData) ->
    {_, Rest} = read_group(Bin, FNum),
    dfp_read_field_def_Emission(Rest, 0, Z2, F@_1,
				TrUserData).

skip_32_Emission(<<_:32, Rest/binary>>, Z1, Z2, F@_1,
		 TrUserData) ->
    dfp_read_field_def_Emission(Rest, Z1, Z2, F@_1,
				TrUserData).

skip_64_Emission(<<_:64, Rest/binary>>, Z1, Z2, F@_1,
		 TrUserData) ->
    dfp_read_field_def_Emission(Rest, Z1, Z2, F@_1,
				TrUserData).

decode_msg_Notification(Bin, TrUserData) ->
    dfp_read_field_def_Notification(Bin, 0, 0,
				    id('$undef', TrUserData),
				    id('$undef', TrUserData),
				    id([], TrUserData), TrUserData).

dfp_read_field_def_Notification(<<10, Rest/binary>>, Z1,
				Z2, F@_1, F@_2, F@_3, TrUserData) ->
    d_field_Notification_status(Rest, Z1, Z2, F@_1, F@_2,
				F@_3, TrUserData);
dfp_read_field_def_Notification(<<18, Rest/binary>>, Z1,
				Z2, F@_1, F@_2, F@_3, TrUserData) ->
    d_field_Notification_action(Rest, Z1, Z2, F@_1, F@_2,
				F@_3, TrUserData);
dfp_read_field_def_Notification(<<26, Rest/binary>>, Z1,
				Z2, F@_1, F@_2, F@_3, TrUserData) ->
    d_field_Notification_company(Rest, Z1, Z2, F@_1, F@_2,
				 F@_3, TrUserData);
dfp_read_field_def_Notification(<<>>, 0, 0, F@_1, F@_2,
				R1, TrUserData) ->
    S1 = #{company => lists_reverse(R1, TrUserData)},
    S2 = if F@_1 == '$undef' -> S1;
	    true -> S1#{status => F@_1}
	 end,
    if F@_2 == '$undef' -> S2;
       true -> S2#{action => F@_2}
    end;
dfp_read_field_def_Notification(Other, Z1, Z2, F@_1,
				F@_2, F@_3, TrUserData) ->
    dg_read_field_def_Notification(Other, Z1, Z2, F@_1,
				   F@_2, F@_3, TrUserData).

dg_read_field_def_Notification(<<1:1, X:7,
				 Rest/binary>>,
			       N, Acc, F@_1, F@_2, F@_3, TrUserData)
    when N < 32 - 7 ->
    dg_read_field_def_Notification(Rest, N + 7,
				   X bsl N + Acc, F@_1, F@_2, F@_3, TrUserData);
dg_read_field_def_Notification(<<0:1, X:7,
				 Rest/binary>>,
			       N, Acc, F@_1, F@_2, F@_3, TrUserData) ->
    Key = X bsl N + Acc,
    case Key of
      10 ->
	  d_field_Notification_status(Rest, 0, 0, F@_1, F@_2,
				      F@_3, TrUserData);
      18 ->
	  d_field_Notification_action(Rest, 0, 0, F@_1, F@_2,
				      F@_3, TrUserData);
      26 ->
	  d_field_Notification_company(Rest, 0, 0, F@_1, F@_2,
				       F@_3, TrUserData);
      _ ->
	  case Key band 7 of
	    0 ->
		skip_varint_Notification(Rest, 0, 0, F@_1, F@_2, F@_3,
					 TrUserData);
	    1 ->
		skip_64_Notification(Rest, 0, 0, F@_1, F@_2, F@_3,
				     TrUserData);
	    2 ->
		skip_length_delimited_Notification(Rest, 0, 0, F@_1,
						   F@_2, F@_3, TrUserData);
	    3 ->
		skip_group_Notification(Rest, Key bsr 3, 0, F@_1, F@_2,
					F@_3, TrUserData);
	    5 ->
		skip_32_Notification(Rest, 0, 0, F@_1, F@_2, F@_3,
				     TrUserData)
	  end
    end;
dg_read_field_def_Notification(<<>>, 0, 0, F@_1, F@_2,
			       R1, TrUserData) ->
    S1 = #{company => lists_reverse(R1, TrUserData)},
    S2 = if F@_1 == '$undef' -> S1;
	    true -> S1#{status => F@_1}
	 end,
    if F@_2 == '$undef' -> S2;
       true -> S2#{action => F@_2}
    end.

d_field_Notification_status(<<1:1, X:7, Rest/binary>>,
			    N, Acc, F@_1, F@_2, F@_3, TrUserData)
    when N < 57 ->
    d_field_Notification_status(Rest, N + 7, X bsl N + Acc,
				F@_1, F@_2, F@_3, TrUserData);
d_field_Notification_status(<<0:1, X:7, Rest/binary>>,
			    N, Acc, _, F@_2, F@_3, TrUserData) ->
    {NewFValue, RestF} = begin
			   Len = X bsl N + Acc,
			   <<Utf8:Len/binary, Rest2/binary>> = Rest,
			   {id(unicode:characters_to_list(Utf8, unicode),
			       TrUserData),
			    Rest2}
			 end,
    dfp_read_field_def_Notification(RestF, 0, 0, NewFValue,
				    F@_2, F@_3, TrUserData).

d_field_Notification_action(<<1:1, X:7, Rest/binary>>,
			    N, Acc, F@_1, F@_2, F@_3, TrUserData)
    when N < 57 ->
    d_field_Notification_action(Rest, N + 7, X bsl N + Acc,
				F@_1, F@_2, F@_3, TrUserData);
d_field_Notification_action(<<0:1, X:7, Rest/binary>>,
			    N, Acc, F@_1, _, F@_3, TrUserData) ->
    {NewFValue, RestF} = begin
			   Len = X bsl N + Acc,
			   <<Utf8:Len/binary, Rest2/binary>> = Rest,
			   {id(unicode:characters_to_list(Utf8, unicode),
			       TrUserData),
			    Rest2}
			 end,
    dfp_read_field_def_Notification(RestF, 0, 0, F@_1,
				    NewFValue, F@_3, TrUserData).

d_field_Notification_company(<<1:1, X:7, Rest/binary>>,
			     N, Acc, F@_1, F@_2, F@_3, TrUserData)
    when N < 57 ->
    d_field_Notification_company(Rest, N + 7, X bsl N + Acc,
				 F@_1, F@_2, F@_3, TrUserData);
d_field_Notification_company(<<0:1, X:7, Rest/binary>>,
			     N, Acc, F@_1, F@_2, Prev, TrUserData) ->
    {NewFValue, RestF} = begin
			   Len = X bsl N + Acc,
			   <<Utf8:Len/binary, Rest2/binary>> = Rest,
			   {id(unicode:characters_to_list(Utf8, unicode),
			       TrUserData),
			    Rest2}
			 end,
    dfp_read_field_def_Notification(RestF, 0, 0, F@_1, F@_2,
				    cons(NewFValue, Prev, TrUserData),
				    TrUserData).

skip_varint_Notification(<<1:1, _:7, Rest/binary>>, Z1,
			 Z2, F@_1, F@_2, F@_3, TrUserData) ->
    skip_varint_Notification(Rest, Z1, Z2, F@_1, F@_2, F@_3,
			     TrUserData);
skip_varint_Notification(<<0:1, _:7, Rest/binary>>, Z1,
			 Z2, F@_1, F@_2, F@_3, TrUserData) ->
    dfp_read_field_def_Notification(Rest, Z1, Z2, F@_1,
				    F@_2, F@_3, TrUserData).

skip_length_delimited_Notification(<<1:1, X:7,
				     Rest/binary>>,
				   N, Acc, F@_1, F@_2, F@_3, TrUserData)
    when N < 57 ->
    skip_length_delimited_Notification(Rest, N + 7,
				       X bsl N + Acc, F@_1, F@_2, F@_3,
				       TrUserData);
skip_length_delimited_Notification(<<0:1, X:7,
				     Rest/binary>>,
				   N, Acc, F@_1, F@_2, F@_3, TrUserData) ->
    Length = X bsl N + Acc,
    <<_:Length/binary, Rest2/binary>> = Rest,
    dfp_read_field_def_Notification(Rest2, 0, 0, F@_1, F@_2,
				    F@_3, TrUserData).

skip_group_Notification(Bin, FNum, Z2, F@_1, F@_2, F@_3,
			TrUserData) ->
    {_, Rest} = read_group(Bin, FNum),
    dfp_read_field_def_Notification(Rest, 0, Z2, F@_1, F@_2,
				    F@_3, TrUserData).

skip_32_Notification(<<_:32, Rest/binary>>, Z1, Z2,
		     F@_1, F@_2, F@_3, TrUserData) ->
    dfp_read_field_def_Notification(Rest, Z1, Z2, F@_1,
				    F@_2, F@_3, TrUserData).

skip_64_Notification(<<_:64, Rest/binary>>, Z1, Z2,
		     F@_1, F@_2, F@_3, TrUserData) ->
    dfp_read_field_def_Notification(Rest, Z1, Z2, F@_1,
				    F@_2, F@_3, TrUserData).

read_group(Bin, FieldNum) ->
    {NumBytes, EndTagLen} = read_gr_b(Bin, 0, 0, 0, 0, FieldNum),
    <<Group:NumBytes/binary, _:EndTagLen/binary, Rest/binary>> = Bin,
    {Group, Rest}.

%% Like skipping over fields, but record the total length,
%% Each field is <(FieldNum bsl 3) bor FieldType> ++ <FieldValue>
%% Record the length because varints may be non-optimally encoded.
%%
%% Groups can be nested, but assume the same FieldNum cannot be nested
%% because group field numbers are shared with the rest of the fields
%% numbers. Thus we can search just for an group-end with the same
%% field number.
%%
%% (The only time the same group field number could occur would
%% be in a nested sub message, but then it would be inside a
%% length-delimited entry, which we skip-read by length.)
read_gr_b(<<1:1, X:7, Tl/binary>>, N, Acc, NumBytes, TagLen, FieldNum)
  when N < (32-7) ->
    read_gr_b(Tl, N+7, X bsl N + Acc, NumBytes, TagLen+1, FieldNum);
read_gr_b(<<0:1, X:7, Tl/binary>>, N, Acc, NumBytes, TagLen,
          FieldNum) ->
    Key = X bsl N + Acc,
    TagLen1 = TagLen + 1,
    case {Key bsr 3, Key band 7} of
        {FieldNum, 4} -> % 4 = group_end
            {NumBytes, TagLen1};
        {_, 0} -> % 0 = varint
            read_gr_vi(Tl, 0, NumBytes + TagLen1, FieldNum);
        {_, 1} -> % 1 = bits64
            <<_:64, Tl2/binary>> = Tl,
            read_gr_b(Tl2, 0, 0, NumBytes + TagLen1 + 8, 0, FieldNum);
        {_, 2} -> % 2 = length_delimited
            read_gr_ld(Tl, 0, 0, NumBytes + TagLen1, FieldNum);
        {_, 3} -> % 3 = group_start
            read_gr_b(Tl, 0, 0, NumBytes + TagLen1, 0, FieldNum);
        {_, 4} -> % 4 = group_end
            read_gr_b(Tl, 0, 0, NumBytes + TagLen1, 0, FieldNum);
        {_, 5} -> % 5 = bits32
            <<_:32, Tl2/binary>> = Tl,
            read_gr_b(Tl2, 0, 0, NumBytes + TagLen1 + 4, 0, FieldNum)
    end.

read_gr_vi(<<1:1, _:7, Tl/binary>>, N, NumBytes, FieldNum)
  when N < (64-7) ->
    read_gr_vi(Tl, N+7, NumBytes+1, FieldNum);
read_gr_vi(<<0:1, _:7, Tl/binary>>, _, NumBytes, FieldNum) ->
    read_gr_b(Tl, 0, 0, NumBytes+1, 0, FieldNum).

read_gr_ld(<<1:1, X:7, Tl/binary>>, N, Acc, NumBytes, FieldNum)
  when N < (64-7) ->
    read_gr_ld(Tl, N+7, X bsl N + Acc, NumBytes+1, FieldNum);
read_gr_ld(<<0:1, X:7, Tl/binary>>, N, Acc, NumBytes, FieldNum) ->
    Len = X bsl N + Acc,
    NumBytes1 = NumBytes + 1,
    <<_:Len/binary, Tl2/binary>> = Tl,
    read_gr_b(Tl2, 0, 0, NumBytes1 + Len, 0, FieldNum).

merge_msgs(Prev, New, MsgName) when is_atom(MsgName) ->
    merge_msgs(Prev, New, MsgName, []).

merge_msgs(Prev, New, MsgName, Opts) ->
    TrUserData = proplists:get_value(user_data, Opts),
    case MsgName of
      'Authentication' ->
	  merge_msg_Authentication(Prev, New, TrUserData);
      'Result' -> merge_msg_Result(Prev, New, TrUserData);
      'Bid' -> merge_msg_Bid(Prev, New, TrUserData);
      'Subscription' ->
	  merge_msg_Subscription(Prev, New, TrUserData);
      'Auction' -> merge_msg_Auction(Prev, New, TrUserData);
      'Emission' -> merge_msg_Emission(Prev, New, TrUserData);
      'Notification' ->
	  merge_msg_Notification(Prev, New, TrUserData)
    end.

-compile({nowarn_unused_function,merge_msg_Authentication/3}).
merge_msg_Authentication(PMsg, NMsg, _) ->
    S1 = #{},
    S2 = case {PMsg, NMsg} of
	   {_, #{username := NFusername}} ->
	       S1#{username => NFusername};
	   {#{username := PFusername}, _} ->
	       S1#{username => PFusername};
	   _ -> S1
	 end,
    case {PMsg, NMsg} of
      {_, #{password := NFpassword}} ->
	  S2#{password => NFpassword};
      {#{password := PFpassword}, _} ->
	  S2#{password => PFpassword};
      _ -> S2
    end.

-compile({nowarn_unused_function,merge_msg_Result/3}).
merge_msg_Result(PMsg, NMsg, _) ->
    S1 = #{},
    S2 = case {PMsg, NMsg} of
	   {_, #{result := NFresult}} -> S1#{result => NFresult};
	   {#{result := PFresult}, _} -> S1#{result => PFresult};
	   _ -> S1
	 end,
    case {PMsg, NMsg} of
      {_, #{entity := NFentity}} -> S2#{entity => NFentity};
      {#{entity := PFentity}, _} -> S2#{entity => PFentity};
      _ -> S2
    end.

-compile({nowarn_unused_function,merge_msg_Bid/3}).
merge_msg_Bid(PMsg, NMsg, _) ->
    S1 = #{},
    S2 = case {PMsg, NMsg} of
	   {_, #{company := NFcompany}} ->
	       S1#{company => NFcompany};
	   {#{company := PFcompany}, _} ->
	       S1#{company => PFcompany};
	   _ -> S1
	 end,
    S3 = case {PMsg, NMsg} of
	   {_, #{amount := NFamount}} -> S2#{amount => NFamount};
	   {#{amount := PFamount}, _} -> S2#{amount => PFamount};
	   _ -> S2
	 end,
    case {PMsg, NMsg} of
      {_, #{interest := NFinterest}} ->
	  S3#{interest => NFinterest};
      {#{interest := PFinterest}, _} ->
	  S3#{interest => PFinterest};
      _ -> S3
    end.

-compile({nowarn_unused_function,merge_msg_Subscription/3}).
merge_msg_Subscription(PMsg, NMsg, _) ->
    S1 = #{},
    S2 = case {PMsg, NMsg} of
	   {_, #{company := NFcompany}} ->
	       S1#{company => NFcompany};
	   {#{company := PFcompany}, _} ->
	       S1#{company => PFcompany};
	   _ -> S1
	 end,
    case {PMsg, NMsg} of
      {_, #{amount := NFamount}} -> S2#{amount => NFamount};
      {#{amount := PFamount}, _} -> S2#{amount => PFamount};
      _ -> S2
    end.

-compile({nowarn_unused_function,merge_msg_Auction/3}).
merge_msg_Auction(PMsg, NMsg, _) ->
    S1 = #{},
    S2 = case {PMsg, NMsg} of
	   {_, #{amount := NFamount}} -> S1#{amount => NFamount};
	   {#{amount := PFamount}, _} -> S1#{amount => PFamount};
	   _ -> S1
	 end,
    case {PMsg, NMsg} of
      {_, #{interest := NFinterest}} ->
	  S2#{interest => NFinterest};
      {#{interest := PFinterest}, _} ->
	  S2#{interest => PFinterest};
      _ -> S2
    end.

-compile({nowarn_unused_function,merge_msg_Emission/3}).
merge_msg_Emission(PMsg, NMsg, _) ->
    S1 = #{},
    case {PMsg, NMsg} of
      {_, #{amount := NFamount}} -> S1#{amount => NFamount};
      {#{amount := PFamount}, _} -> S1#{amount => PFamount};
      _ -> S1
    end.

-compile({nowarn_unused_function,merge_msg_Notification/3}).
merge_msg_Notification(PMsg, NMsg, TrUserData) ->
    S1 = #{},
    S2 = case {PMsg, NMsg} of
	   {_, #{status := NFstatus}} -> S1#{status => NFstatus};
	   {#{status := PFstatus}, _} -> S1#{status => PFstatus};
	   _ -> S1
	 end,
    S3 = case {PMsg, NMsg} of
	   {_, #{action := NFaction}} -> S2#{action => NFaction};
	   {#{action := PFaction}, _} -> S2#{action => PFaction};
	   _ -> S2
	 end,
    case {PMsg, NMsg} of
      {#{company := PFcompany}, #{company := NFcompany}} ->
	  S3#{company =>
		  'erlang_++'(PFcompany, NFcompany, TrUserData)};
      {_, #{company := NFcompany}} ->
	  S3#{company => NFcompany};
      {#{company := PFcompany}, _} ->
	  S3#{company => PFcompany};
      {_, _} -> S3
    end.


verify_msg(Msg, MsgName) when is_atom(MsgName) ->
    verify_msg(Msg, MsgName, []).

verify_msg(Msg, MsgName, Opts) ->
    TrUserData = proplists:get_value(user_data, Opts),
    case MsgName of
      'Authentication' ->
	  v_msg_Authentication(Msg, [MsgName], TrUserData);
      'Result' -> v_msg_Result(Msg, [MsgName], TrUserData);
      'Bid' -> v_msg_Bid(Msg, [MsgName], TrUserData);
      'Subscription' ->
	  v_msg_Subscription(Msg, [MsgName], TrUserData);
      'Auction' -> v_msg_Auction(Msg, [MsgName], TrUserData);
      'Emission' ->
	  v_msg_Emission(Msg, [MsgName], TrUserData);
      'Notification' ->
	  v_msg_Notification(Msg, [MsgName], TrUserData);
      _ -> mk_type_error(not_a_known_message, Msg, [])
    end.


-compile({nowarn_unused_function,v_msg_Authentication/3}).
-dialyzer({nowarn_function,v_msg_Authentication/3}).
v_msg_Authentication(#{} = M, Path, TrUserData) ->
    case M of
      #{username := F1} ->
	  v_type_string(F1, [username | Path], TrUserData);
      _ -> ok
    end,
    case M of
      #{password := F2} ->
	  v_type_string(F2, [password | Path], TrUserData);
      _ -> ok
    end,
    lists:foreach(fun (username) -> ok;
		      (password) -> ok;
		      (OtherKey) ->
			  mk_type_error({extraneous_key, OtherKey}, M, Path)
		  end,
		  maps:keys(M)),
    ok;
v_msg_Authentication(M, Path, _TrUserData)
    when is_map(M) ->
    mk_type_error({missing_fields, [] -- maps:keys(M),
		   'Authentication'},
		  M, Path);
v_msg_Authentication(X, Path, _TrUserData) ->
    mk_type_error({expected_msg, 'Authentication'}, X,
		  Path).

-compile({nowarn_unused_function,v_msg_Result/3}).
-dialyzer({nowarn_function,v_msg_Result/3}).
v_msg_Result(#{} = M, Path, TrUserData) ->
    case M of
      #{result := F1} ->
	  v_type_bool(F1, [result | Path], TrUserData);
      _ -> ok
    end,
    case M of
      #{entity := F2} ->
	  v_type_string(F2, [entity | Path], TrUserData);
      _ -> ok
    end,
    lists:foreach(fun (result) -> ok;
		      (entity) -> ok;
		      (OtherKey) ->
			  mk_type_error({extraneous_key, OtherKey}, M, Path)
		  end,
		  maps:keys(M)),
    ok;
v_msg_Result(M, Path, _TrUserData) when is_map(M) ->
    mk_type_error({missing_fields, [] -- maps:keys(M),
		   'Result'},
		  M, Path);
v_msg_Result(X, Path, _TrUserData) ->
    mk_type_error({expected_msg, 'Result'}, X, Path).

-compile({nowarn_unused_function,v_msg_Bid/3}).
-dialyzer({nowarn_function,v_msg_Bid/3}).
v_msg_Bid(#{} = M, Path, TrUserData) ->
    case M of
      #{company := F1} ->
	  v_type_string(F1, [company | Path], TrUserData);
      _ -> ok
    end,
    case M of
      #{amount := F2} ->
	  v_type_int32(F2, [amount | Path], TrUserData);
      _ -> ok
    end,
    case M of
      #{interest := F3} ->
	  v_type_int32(F3, [interest | Path], TrUserData);
      _ -> ok
    end,
    lists:foreach(fun (company) -> ok;
		      (amount) -> ok;
		      (interest) -> ok;
		      (OtherKey) ->
			  mk_type_error({extraneous_key, OtherKey}, M, Path)
		  end,
		  maps:keys(M)),
    ok;
v_msg_Bid(M, Path, _TrUserData) when is_map(M) ->
    mk_type_error({missing_fields, [] -- maps:keys(M),
		   'Bid'},
		  M, Path);
v_msg_Bid(X, Path, _TrUserData) ->
    mk_type_error({expected_msg, 'Bid'}, X, Path).

-compile({nowarn_unused_function,v_msg_Subscription/3}).
-dialyzer({nowarn_function,v_msg_Subscription/3}).
v_msg_Subscription(#{} = M, Path, TrUserData) ->
    case M of
      #{company := F1} ->
	  v_type_string(F1, [company | Path], TrUserData);
      _ -> ok
    end,
    case M of
      #{amount := F2} ->
	  v_type_int32(F2, [amount | Path], TrUserData);
      _ -> ok
    end,
    lists:foreach(fun (company) -> ok;
		      (amount) -> ok;
		      (OtherKey) ->
			  mk_type_error({extraneous_key, OtherKey}, M, Path)
		  end,
		  maps:keys(M)),
    ok;
v_msg_Subscription(M, Path, _TrUserData)
    when is_map(M) ->
    mk_type_error({missing_fields, [] -- maps:keys(M),
		   'Subscription'},
		  M, Path);
v_msg_Subscription(X, Path, _TrUserData) ->
    mk_type_error({expected_msg, 'Subscription'}, X, Path).

-compile({nowarn_unused_function,v_msg_Auction/3}).
-dialyzer({nowarn_function,v_msg_Auction/3}).
v_msg_Auction(#{} = M, Path, TrUserData) ->
    case M of
      #{amount := F1} ->
	  v_type_int32(F1, [amount | Path], TrUserData);
      _ -> ok
    end,
    case M of
      #{interest := F2} ->
	  v_type_int32(F2, [interest | Path], TrUserData);
      _ -> ok
    end,
    lists:foreach(fun (amount) -> ok;
		      (interest) -> ok;
		      (OtherKey) ->
			  mk_type_error({extraneous_key, OtherKey}, M, Path)
		  end,
		  maps:keys(M)),
    ok;
v_msg_Auction(M, Path, _TrUserData) when is_map(M) ->
    mk_type_error({missing_fields, [] -- maps:keys(M),
		   'Auction'},
		  M, Path);
v_msg_Auction(X, Path, _TrUserData) ->
    mk_type_error({expected_msg, 'Auction'}, X, Path).

-compile({nowarn_unused_function,v_msg_Emission/3}).
-dialyzer({nowarn_function,v_msg_Emission/3}).
v_msg_Emission(#{} = M, Path, TrUserData) ->
    case M of
      #{amount := F1} ->
	  v_type_int32(F1, [amount | Path], TrUserData);
      _ -> ok
    end,
    lists:foreach(fun (amount) -> ok;
		      (OtherKey) ->
			  mk_type_error({extraneous_key, OtherKey}, M, Path)
		  end,
		  maps:keys(M)),
    ok;
v_msg_Emission(M, Path, _TrUserData) when is_map(M) ->
    mk_type_error({missing_fields, [] -- maps:keys(M),
		   'Emission'},
		  M, Path);
v_msg_Emission(X, Path, _TrUserData) ->
    mk_type_error({expected_msg, 'Emission'}, X, Path).

-compile({nowarn_unused_function,v_msg_Notification/3}).
-dialyzer({nowarn_function,v_msg_Notification/3}).
v_msg_Notification(#{} = M, Path, TrUserData) ->
    case M of
      #{status := F1} ->
	  v_type_string(F1, [status | Path], TrUserData);
      _ -> ok
    end,
    case M of
      #{action := F2} ->
	  v_type_string(F2, [action | Path], TrUserData);
      _ -> ok
    end,
    case M of
      #{company := F3} ->
	  if is_list(F3) ->
		 _ = [v_type_string(Elem, [company | Path], TrUserData)
		      || Elem <- F3],
		 ok;
	     true ->
		 mk_type_error({invalid_list_of, string}, F3,
			       [company | Path])
	  end;
      _ -> ok
    end,
    lists:foreach(fun (status) -> ok;
		      (action) -> ok;
		      (company) -> ok;
		      (OtherKey) ->
			  mk_type_error({extraneous_key, OtherKey}, M, Path)
		  end,
		  maps:keys(M)),
    ok;
v_msg_Notification(M, Path, _TrUserData)
    when is_map(M) ->
    mk_type_error({missing_fields, [] -- maps:keys(M),
		   'Notification'},
		  M, Path);
v_msg_Notification(X, Path, _TrUserData) ->
    mk_type_error({expected_msg, 'Notification'}, X, Path).

-compile({nowarn_unused_function,v_type_int32/3}).
-dialyzer({nowarn_function,v_type_int32/3}).
v_type_int32(N, _Path, _TrUserData)
    when -2147483648 =< N, N =< 2147483647 ->
    ok;
v_type_int32(N, Path, _TrUserData) when is_integer(N) ->
    mk_type_error({value_out_of_range, int32, signed, 32},
		  N, Path);
v_type_int32(X, Path, _TrUserData) ->
    mk_type_error({bad_integer, int32, signed, 32}, X,
		  Path).

-compile({nowarn_unused_function,v_type_bool/3}).
-dialyzer({nowarn_function,v_type_bool/3}).
v_type_bool(false, _Path, _TrUserData) -> ok;
v_type_bool(true, _Path, _TrUserData) -> ok;
v_type_bool(0, _Path, _TrUserData) -> ok;
v_type_bool(1, _Path, _TrUserData) -> ok;
v_type_bool(X, Path, _TrUserData) ->
    mk_type_error(bad_boolean_value, X, Path).

-compile({nowarn_unused_function,v_type_string/3}).
-dialyzer({nowarn_function,v_type_string/3}).
v_type_string(S, Path, _TrUserData)
    when is_list(S); is_binary(S) ->
    try unicode:characters_to_binary(S) of
      B when is_binary(B) -> ok;
      {error, _, _} ->
	  mk_type_error(bad_unicode_string, S, Path)
    catch
      error:badarg ->
	  mk_type_error(bad_unicode_string, S, Path)
    end;
v_type_string(X, Path, _TrUserData) ->
    mk_type_error(bad_unicode_string, X, Path).

-compile({nowarn_unused_function,mk_type_error/3}).
-spec mk_type_error(_, _, list()) -> no_return().
mk_type_error(Error, ValueSeen, Path) ->
    Path2 = prettify_path(Path),
    erlang:error({gpb_type_error,
		  {Error, [{value, ValueSeen}, {path, Path2}]}}).


-compile({nowarn_unused_function,prettify_path/1}).
-dialyzer({nowarn_function,prettify_path/1}).
prettify_path([]) -> top_level;
prettify_path(PathR) ->
    list_to_atom(lists:append(lists:join(".",
					 lists:map(fun atom_to_list/1,
						   lists:reverse(PathR))))).


-compile({nowarn_unused_function,id/2}).
-compile({inline,id/2}).
id(X, _TrUserData) -> X.

-compile({nowarn_unused_function,v_ok/3}).
-compile({inline,v_ok/3}).
v_ok(_Value, _Path, _TrUserData) -> ok.

-compile({nowarn_unused_function,m_overwrite/3}).
-compile({inline,m_overwrite/3}).
m_overwrite(_Prev, New, _TrUserData) -> New.

-compile({nowarn_unused_function,cons/3}).
-compile({inline,cons/3}).
cons(Elem, Acc, _TrUserData) -> [Elem | Acc].

-compile({nowarn_unused_function,lists_reverse/2}).
-compile({inline,lists_reverse/2}).
'lists_reverse'(L, _TrUserData) -> lists:reverse(L).
-compile({nowarn_unused_function,'erlang_++'/3}).
-compile({inline,'erlang_++'/3}).
'erlang_++'(A, B, _TrUserData) -> A ++ B.

get_msg_defs() ->
    [{{msg, 'Authentication'},
      [#{name => username, fnum => 1, rnum => 2,
	 type => string, occurrence => optional, opts => []},
       #{name => password, fnum => 2, rnum => 3,
	 type => string, occurrence => optional, opts => []}]},
     {{msg, 'Result'},
      [#{name => result, fnum => 1, rnum => 2, type => bool,
	 occurrence => optional, opts => []},
       #{name => entity, fnum => 3, rnum => 3, type => string,
	 occurrence => optional, opts => []}]},
     {{msg, 'Bid'},
      [#{name => company, fnum => 1, rnum => 2,
	 type => string, occurrence => optional, opts => []},
       #{name => amount, fnum => 2, rnum => 3, type => int32,
	 occurrence => optional, opts => []},
       #{name => interest, fnum => 3, rnum => 4, type => int32,
	 occurrence => optional, opts => []}]},
     {{msg, 'Subscription'},
      [#{name => company, fnum => 1, rnum => 2,
	 type => string, occurrence => optional, opts => []},
       #{name => amount, fnum => 2, rnum => 3, type => int32,
	 occurrence => optional, opts => []}]},
     {{msg, 'Auction'},
      [#{name => amount, fnum => 1, rnum => 2, type => int32,
	 occurrence => optional, opts => []},
       #{name => interest, fnum => 2, rnum => 3, type => int32,
	 occurrence => optional, opts => []}]},
     {{msg, 'Emission'},
      [#{name => amount, fnum => 1, rnum => 2, type => int32,
	 occurrence => optional, opts => []}]},
     {{msg, 'Notification'},
      [#{name => status, fnum => 1, rnum => 2, type => string,
	 occurrence => optional, opts => []},
       #{name => action, fnum => 2, rnum => 3, type => string,
	 occurrence => optional, opts => []},
       #{name => company, fnum => 3, rnum => 4, type => string,
	 occurrence => repeated, opts => []}]}].


get_msg_names() ->
    ['Authentication', 'Result', 'Bid', 'Subscription',
     'Auction', 'Emission', 'Notification'].


get_group_names() -> [].


get_msg_or_group_names() ->
    ['Authentication', 'Result', 'Bid', 'Subscription',
     'Auction', 'Emission', 'Notification'].


get_enum_names() -> [].


fetch_msg_def(MsgName) ->
    case find_msg_def(MsgName) of
      Fs when is_list(Fs) -> Fs;
      error -> erlang:error({no_such_msg, MsgName})
    end.


-spec fetch_enum_def(_) -> no_return().
fetch_enum_def(EnumName) ->
    erlang:error({no_such_enum, EnumName}).


find_msg_def('Authentication') ->
    [#{name => username, fnum => 1, rnum => 2,
       type => string, occurrence => optional, opts => []},
     #{name => password, fnum => 2, rnum => 3,
       type => string, occurrence => optional, opts => []}];
find_msg_def('Result') ->
    [#{name => result, fnum => 1, rnum => 2, type => bool,
       occurrence => optional, opts => []},
     #{name => entity, fnum => 3, rnum => 3, type => string,
       occurrence => optional, opts => []}];
find_msg_def('Bid') ->
    [#{name => company, fnum => 1, rnum => 2,
       type => string, occurrence => optional, opts => []},
     #{name => amount, fnum => 2, rnum => 3, type => int32,
       occurrence => optional, opts => []},
     #{name => interest, fnum => 3, rnum => 4, type => int32,
       occurrence => optional, opts => []}];
find_msg_def('Subscription') ->
    [#{name => company, fnum => 1, rnum => 2,
       type => string, occurrence => optional, opts => []},
     #{name => amount, fnum => 2, rnum => 3, type => int32,
       occurrence => optional, opts => []}];
find_msg_def('Auction') ->
    [#{name => amount, fnum => 1, rnum => 2, type => int32,
       occurrence => optional, opts => []},
     #{name => interest, fnum => 2, rnum => 3, type => int32,
       occurrence => optional, opts => []}];
find_msg_def('Emission') ->
    [#{name => amount, fnum => 1, rnum => 2, type => int32,
       occurrence => optional, opts => []}];
find_msg_def('Notification') ->
    [#{name => status, fnum => 1, rnum => 2, type => string,
       occurrence => optional, opts => []},
     #{name => action, fnum => 2, rnum => 3, type => string,
       occurrence => optional, opts => []},
     #{name => company, fnum => 3, rnum => 4, type => string,
       occurrence => repeated, opts => []}];
find_msg_def(_) -> error.


find_enum_def(_) -> error.


-spec enum_symbol_by_value(_, _) -> no_return().
enum_symbol_by_value(E, V) ->
    erlang:error({no_enum_defs, E, V}).


-spec enum_value_by_symbol(_, _) -> no_return().
enum_value_by_symbol(E, V) ->
    erlang:error({no_enum_defs, E, V}).



get_service_names() -> [].


get_service_def(_) -> error.


get_rpc_names(_) -> error.


find_rpc_def(_, _) -> error.



-spec fetch_rpc_def(_, _) -> no_return().
fetch_rpc_def(ServiceName, RpcName) ->
    erlang:error({no_such_rpc, ServiceName, RpcName}).


%% Convert a a fully qualified (ie with package name) service name
%% as a binary to a service name as an atom.
-spec fqbin_to_service_name(_) -> no_return().
fqbin_to_service_name(X) ->
    error({gpb_error, {badservice, X}}).


%% Convert a service name as an atom to a fully qualified

%% (ie with package name) name as a binary.
-spec service_name_to_fqbin(_) -> no_return().
service_name_to_fqbin(X) ->
    error({gpb_error, {badservice, X}}).


%% Convert a a fully qualified (ie with package name) service name
%% and an rpc name, both as binaries to a service name and an rpc
%% name, as atoms.
-spec fqbins_to_service_and_rpc_name(_, _) -> no_return().
fqbins_to_service_and_rpc_name(S, R) ->
    error({gpb_error, {badservice_or_rpc, {S, R}}}).


%% Convert a service name and an rpc name, both as atoms,
%% to a fully qualified (ie with package name) service name and
%% an rpc name as binaries.
-spec service_and_rpc_name_to_fqbins(_, _) -> no_return().
service_and_rpc_name_to_fqbins(S, R) ->
    error({gpb_error, {badservice_or_rpc, {S, R}}}).


get_package_name() -> undefined.


%% Whether or not the message names
%% are prepended with package name or not.
uses_packages() -> false.



gpb_version_as_string() ->
    "4.5.1".

gpb_version_as_list() ->
    [4,5,1].
